// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// APIProductVersionFilterDimension - The dimension to filter.
type APIProductVersionFilterDimension string

const (
	APIProductVersionFilterDimensionAPIProductVersion APIProductVersionFilterDimension = "API_PRODUCT_VERSION"
)

func (e APIProductVersionFilterDimension) ToPointer() *APIProductVersionFilterDimension {
	return &e
}
func (e *APIProductVersionFilterDimension) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "API_PRODUCT_VERSION":
		*e = APIProductVersionFilterDimension(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIProductVersionFilterDimension: %v", v)
	}
}

type APIProductVersionFilter struct {
	// The dimension to filter.
	Dimension APIProductVersionFilterDimension `json:"dimension"`
	// The type of filter to apply.  `IN` filters will limit results to only the specified values, while `NOT_IN` filters will exclude the specified values.
	Type FilterType `json:"type"`
	// The UUIDs of the API product versions to include in the results.
	//
	Values []string `json:"values"`
}

func (o *APIProductVersionFilter) GetDimension() APIProductVersionFilterDimension {
	if o == nil {
		return APIProductVersionFilterDimension("")
	}
	return o.Dimension
}

func (o *APIProductVersionFilter) GetType() FilterType {
	if o == nil {
		return FilterType("")
	}
	return o.Type
}

func (o *APIProductVersionFilter) GetValues() []string {
	if o == nil {
		return []string{}
	}
	return o.Values
}
