// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ControlPlaneFilterDimension - The dimension to filter.
type ControlPlaneFilterDimension string

const (
	ControlPlaneFilterDimensionControlPlane ControlPlaneFilterDimension = "CONTROL_PLANE"
)

func (e ControlPlaneFilterDimension) ToPointer() *ControlPlaneFilterDimension {
	return &e
}
func (e *ControlPlaneFilterDimension) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CONTROL_PLANE":
		*e = ControlPlaneFilterDimension(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ControlPlaneFilterDimension: %v", v)
	}
}

type ControlPlaneFilter struct {
	// The dimension to filter.
	Dimension ControlPlaneFilterDimension `json:"dimension"`
	// The type of filter to apply.  `IN` filters will limit results to only the specified values, while `NOT_IN` filters will exclude the specified values.
	Type FilterType `json:"type"`
	// The UUIDs of the control planes to include in the results.
	//
	Values []string `json:"values"`
}

func (o *ControlPlaneFilter) GetDimension() ControlPlaneFilterDimension {
	if o == nil {
		return ControlPlaneFilterDimension("")
	}
	return o.Dimension
}

func (o *ControlPlaneFilter) GetType() FilterType {
	if o == nil {
		return FilterType("")
	}
	return o.Type
}

func (o *ControlPlaneFilter) GetValues() []string {
	if o == nil {
		return []string{}
	}
	return o.Values
}
