// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/models/components"
)

// ReportCollection - A paginated list response for a collection of reports.
type ReportCollection struct {
	// Returns pagination information
	Meta *components.PaginatedMeta `json:"meta,omitempty"`
	Data []ReportCollectionReport  `json:"data,omitempty"`
}

func (o *ReportCollection) GetMeta() *components.PaginatedMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *ReportCollection) GetData() []ReportCollectionReport {
	if o == nil {
		return nil
	}
	return o.Data
}
