// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/konnect-orchestrator/internal/reports/utils"
)

type ReportCollectionReport struct {
	Name *string `json:"name,omitempty"`

}

func (r ReportCollectionReport) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReportCollectionReport) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReportCollectionReport) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
