quiet: False
inpackage: True
disable-version-string: True
with-expecter: True

filename: "{{.InterfaceName | lower}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"

issue-845-fix: True

packages:
  github.com/Kong/konnect-orchestrator/internal/organization/team:
    interfaces:
      TeamService:
      TeamMembershipService:
  github.com/Kong/konnect-orchestrator/internal/organization/user:
    interfaces:
      UserService:
      InviteService:
  github.com/Kong/konnect-orchestrator/internal/organization/role:
    interfaces:
      RoleService:
  github.com/Kong/konnect-orchestrator/internal/gateway:
    interfaces:
      ControlPlaneService:
