// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/konnect-orchestrator/internal/reports/components"
	"net/http"
)

type UpdateReportRequest struct {
	// The report's ID
	ReportID string `pathParam:"style=simple,explode=false,name=reportId"`
	// The request schema for the update report request.
	Report *components.ReportInput `request:"mediaType=application/json"`
}

func (o *UpdateReportRequest) GetReportID() string {
	if o == nil {
		return ""
	}
	return o.ReportID
}

func (o *UpdateReportRequest) GetReport() *components.ReportInput {
	if o == nil {
		return nil
	}
	return o.Report
}

type UpdateReportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A response including a single report.
	Report *components.Report
}

func (o *UpdateReportResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateReportResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateReportResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateReportResponse) GetReport() *components.Report {
	if o == nil {
		return nil
	}
	return o.Report
}
