// Code generated by mockery. DO NOT EDIT.

package gateway

import (
	context "context"

	components "github.com/Kong/sdk-konnect-go/models/components"

	mock "github.com/stretchr/testify/mock"

	operations "github.com/Kong/sdk-konnect-go/models/operations"
)

// MockControlPlaneService is an autogenerated mock type for the ControlPlaneService type
type MockControlPlaneService struct {
	mock.Mock
}

type MockControlPlaneService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControlPlaneService) EXPECT() *MockControlPlaneService_Expecter {
	return &MockControlPlaneService_Expecter{mock: &_m.Mock}
}

// CreateControlPlane provides a mock function with given fields: ctx, request, opts
func (_m *MockControlPlaneService) CreateControlPlane(ctx context.Context, request components.CreateControlPlaneRequest, opts ...operations.Option) (*operations.CreateControlPlaneResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, request)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateControlPlane")
	}

	var r0 *operations.CreateControlPlaneResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) (*operations.CreateControlPlaneResponse, error)); ok {
		return rf(ctx, request, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) *operations.CreateControlPlaneResponse); ok {
		r0 = rf(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateControlPlaneResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneService_CreateControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateControlPlane'
type MockControlPlaneService_CreateControlPlane_Call struct {
	*mock.Call
}

// CreateControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - request components.CreateControlPlaneRequest
//   - opts ...operations.Option
func (_e *MockControlPlaneService_Expecter) CreateControlPlane(ctx interface{}, request interface{}, opts ...interface{}) *MockControlPlaneService_CreateControlPlane_Call {
	return &MockControlPlaneService_CreateControlPlane_Call{Call: _e.mock.On("CreateControlPlane",
		append([]interface{}{ctx, request}, opts...)...)}
}

func (_c *MockControlPlaneService_CreateControlPlane_Call) Run(run func(ctx context.Context, request components.CreateControlPlaneRequest, opts ...operations.Option)) *MockControlPlaneService_CreateControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(components.CreateControlPlaneRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneService_CreateControlPlane_Call) Return(_a0 *operations.CreateControlPlaneResponse, _a1 error) *MockControlPlaneService_CreateControlPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneService_CreateControlPlane_Call) RunAndReturn(run func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) (*operations.CreateControlPlaneResponse, error)) *MockControlPlaneService_CreateControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// ListControlPlanes provides a mock function with given fields: ctx, request, opts
func (_m *MockControlPlaneService) ListControlPlanes(ctx context.Context, request operations.ListControlPlanesRequest, opts ...operations.Option) (*operations.ListControlPlanesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, request)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListControlPlanes")
	}

	var r0 *operations.ListControlPlanesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) (*operations.ListControlPlanesResponse, error)); ok {
		return rf(ctx, request, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) *operations.ListControlPlanesResponse); ok {
		r0 = rf(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListControlPlanesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneService_ListControlPlanes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListControlPlanes'
type MockControlPlaneService_ListControlPlanes_Call struct {
	*mock.Call
}

// ListControlPlanes is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListControlPlanesRequest
//   - opts ...operations.Option
func (_e *MockControlPlaneService_Expecter) ListControlPlanes(ctx interface{}, request interface{}, opts ...interface{}) *MockControlPlaneService_ListControlPlanes_Call {
	return &MockControlPlaneService_ListControlPlanes_Call{Call: _e.mock.On("ListControlPlanes",
		append([]interface{}{ctx, request}, opts...)...)}
}

func (_c *MockControlPlaneService_ListControlPlanes_Call) Run(run func(ctx context.Context, request operations.ListControlPlanesRequest, opts ...operations.Option)) *MockControlPlaneService_ListControlPlanes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(operations.ListControlPlanesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneService_ListControlPlanes_Call) Return(_a0 *operations.ListControlPlanesResponse, _a1 error) *MockControlPlaneService_ListControlPlanes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneService_ListControlPlanes_Call) RunAndReturn(run func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) (*operations.ListControlPlanesResponse, error)) *MockControlPlaneService_ListControlPlanes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateControlPlane provides a mock function with given fields: ctx, id, request, opts
func (_m *MockControlPlaneService) UpdateControlPlane(ctx context.Context, id string, request components.UpdateControlPlaneRequest, opts ...operations.Option) (*operations.UpdateControlPlaneResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, request)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateControlPlane")
	}

	var r0 *operations.UpdateControlPlaneResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) (*operations.UpdateControlPlaneResponse, error)); ok {
		return rf(ctx, id, request, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) *operations.UpdateControlPlaneResponse); ok {
		r0 = rf(ctx, id, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpdateControlPlaneResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, id, request, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneService_UpdateControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateControlPlane'
type MockControlPlaneService_UpdateControlPlane_Call struct {
	*mock.Call
}

// UpdateControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request components.UpdateControlPlaneRequest
//   - opts ...operations.Option
func (_e *MockControlPlaneService_Expecter) UpdateControlPlane(ctx interface{}, id interface{}, request interface{}, opts ...interface{}) *MockControlPlaneService_UpdateControlPlane_Call {
	return &MockControlPlaneService_UpdateControlPlane_Call{Call: _e.mock.On("UpdateControlPlane",
		append([]interface{}{ctx, id, request}, opts...)...)}
}

func (_c *MockControlPlaneService_UpdateControlPlane_Call) Run(run func(ctx context.Context, id string, request components.UpdateControlPlaneRequest, opts ...operations.Option)) *MockControlPlaneService_UpdateControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(components.UpdateControlPlaneRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneService_UpdateControlPlane_Call) Return(_a0 *operations.UpdateControlPlaneResponse, _a1 error) *MockControlPlaneService_UpdateControlPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneService_UpdateControlPlane_Call) RunAndReturn(run func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) (*operations.UpdateControlPlaneResponse, error)) *MockControlPlaneService_UpdateControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockControlPlaneService creates a new instance of MockControlPlaneService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControlPlaneService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControlPlaneService {
	mock := &MockControlPlaneService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
