// Code generated by mockery. DO NOT EDIT.

package team

import (
	context "context"

	components "github.com/Kong/sdk-konnect-go/models/components"

	mock "github.com/stretchr/testify/mock"

	operations "github.com/Kong/sdk-konnect-go/models/operations"
)

// MockTeamMembershipService is an autogenerated mock type for the TeamMembershipService type
type MockTeamMembershipService struct {
	mock.Mock
}

type MockTeamMembershipService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamMembershipService) EXPECT() *MockTeamMembershipService_Expecter {
	return &MockTeamMembershipService_Expecter{mock: &_m.Mock}
}

// AddUserToTeam provides a mock function with given fields: ctx, teamID, addUserToTeam, opts
func (_m *MockTeamMembershipService) AddUserToTeam(ctx context.Context, teamID string, addUserToTeam *components.AddUserToTeam, opts ...operations.Option) (*operations.AddUserToTeamResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, teamID, addUserToTeam)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToTeam")
	}

	var r0 *operations.AddUserToTeamResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *components.AddUserToTeam, ...operations.Option) (*operations.AddUserToTeamResponse, error)); ok {
		return rf(ctx, teamID, addUserToTeam, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *components.AddUserToTeam, ...operations.Option) *operations.AddUserToTeamResponse); ok {
		r0 = rf(ctx, teamID, addUserToTeam, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.AddUserToTeamResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *components.AddUserToTeam, ...operations.Option) error); ok {
		r1 = rf(ctx, teamID, addUserToTeam, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamMembershipService_AddUserToTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToTeam'
type MockTeamMembershipService_AddUserToTeam_Call struct {
	*mock.Call
}

// AddUserToTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - addUserToTeam *components.AddUserToTeam
//   - opts ...operations.Option
func (_e *MockTeamMembershipService_Expecter) AddUserToTeam(ctx interface{}, teamID interface{}, addUserToTeam interface{}, opts ...interface{}) *MockTeamMembershipService_AddUserToTeam_Call {
	return &MockTeamMembershipService_AddUserToTeam_Call{Call: _e.mock.On("AddUserToTeam",
		append([]interface{}{ctx, teamID, addUserToTeam}, opts...)...)}
}

func (_c *MockTeamMembershipService_AddUserToTeam_Call) Run(run func(ctx context.Context, teamID string, addUserToTeam *components.AddUserToTeam, opts ...operations.Option)) *MockTeamMembershipService_AddUserToTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(*components.AddUserToTeam), variadicArgs...)
	})
	return _c
}

func (_c *MockTeamMembershipService_AddUserToTeam_Call) Return(_a0 *operations.AddUserToTeamResponse, _a1 error) *MockTeamMembershipService_AddUserToTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamMembershipService_AddUserToTeam_Call) RunAndReturn(run func(context.Context, string, *components.AddUserToTeam, ...operations.Option) (*operations.AddUserToTeamResponse, error)) *MockTeamMembershipService_AddUserToTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeamUsers provides a mock function with given fields: ctx, request, opts
func (_m *MockTeamMembershipService) ListTeamUsers(ctx context.Context, request operations.ListTeamUsersRequest, opts ...operations.Option) (*operations.ListTeamUsersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, request)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListTeamUsers")
	}

	var r0 *operations.ListTeamUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, operations.ListTeamUsersRequest, ...operations.Option) (*operations.ListTeamUsersResponse, error)); ok {
		return rf(ctx, request, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, operations.ListTeamUsersRequest, ...operations.Option) *operations.ListTeamUsersResponse); ok {
		r0 = rf(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListTeamUsersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, operations.ListTeamUsersRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamMembershipService_ListTeamUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeamUsers'
type MockTeamMembershipService_ListTeamUsers_Call struct {
	*mock.Call
}

// ListTeamUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListTeamUsersRequest
//   - opts ...operations.Option
func (_e *MockTeamMembershipService_Expecter) ListTeamUsers(ctx interface{}, request interface{}, opts ...interface{}) *MockTeamMembershipService_ListTeamUsers_Call {
	return &MockTeamMembershipService_ListTeamUsers_Call{Call: _e.mock.On("ListTeamUsers",
		append([]interface{}{ctx, request}, opts...)...)}
}

func (_c *MockTeamMembershipService_ListTeamUsers_Call) Run(run func(ctx context.Context, request operations.ListTeamUsersRequest, opts ...operations.Option)) *MockTeamMembershipService_ListTeamUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(operations.ListTeamUsersRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockTeamMembershipService_ListTeamUsers_Call) Return(_a0 *operations.ListTeamUsersResponse, _a1 error) *MockTeamMembershipService_ListTeamUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamMembershipService_ListTeamUsers_Call) RunAndReturn(run func(context.Context, operations.ListTeamUsersRequest, ...operations.Option) (*operations.ListTeamUsersResponse, error)) *MockTeamMembershipService_ListTeamUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamMembershipService creates a new instance of MockTeamMembershipService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamMembershipService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamMembershipService {
	mock := &MockTeamMembershipService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
