name: release

on:
  push:
    tags:
      - 'v*.*'

env:
  GOPRIVATE: github.com/Kong/*

jobs:
  goreleaser:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PRIVATE_READ }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2' 
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
      - name: Build and push UI Docker image
        id: ui-build-push
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          file: ./ui//Dockerfile
          push: true
          tags: ghcr.io/kong/koctl-ui:latest, ghcr.io/kong/koctl-ui:${{ github.ref_name }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
